import { useState } from 'react'
import ProjectModal from '../../components/ProjectModal'

const projects = [
  {"title": "Maryzeet", "category": "logo", "preview": "/projects_updated/fjbf/maryzeet/Artboard 2.png", "description": "Projekt 'Maryzeet' reprezentuje čistý a minimalistický přístup k designu značky. Zaměřili jsme se na harmonii mezi moderním písmem a tradiční kompozicí, aby logo působilo seriózně, a přitom přístupně. Součástí vizuální identity je i návrh základních aplikací jako vizitky a hlavičkový papír.", "images": ["/projects_updated/fjbf/maryzeet/Artboard 2.png", "/projects_updated/fjbf/maryzeet/Artboard 9.png", "/projects_updated/fjbf/maryzeet/Artboard 19.png"]},
  {"title": "Newdity", "category": "logo", "preview": "/projects_updated/fjbf/newdity/Artboard 15.png", "description": "Newdity je vizuální identita pro technologickou platformu s důrazem na budoucnost a otevřenost. Dominují jí lineární geometrické prvky, neutrální paleta a výrazná typografie. Design reflektuje technologické jádro značky i její komunitní rozměr.", "images": ["/projects_updated/fjbf/newdity/Artboard 7.png", "/projects_updated/fjbf/newdity/Artboard 15.png", "/projects_updated/fjbf/newdity/Artboard 16.png", "/projects_updated/fjbf/newdity/Artboard 17.png", "/projects_updated/fjbf/newdity/Artboard 18.png"]},
  {"title": "Gastronauti", "category": "web", "preview": "/projects_updated/fjbf/gastronauti/Artboard 5.png", "description": "Gastronauti je food brand propojující webové i tiskové výstupy. Vizuální styl je postaven na práci s texturou a vrstvením. Layout je neformální, ale precizně strukturovaný – cílem je přiblížit obsah komunitní cílovce prostřednictvím autentických vizuálů.", "images": ["/projects_updated/fjbf/gastronauti/Artboard 5.png", "/projects_updated/fjbf/gastronauti/Artboard 12.png", "/projects_updated/fjbf/gastronauti/Artboard 13.png"]},
  {"title": "Plakáty pro BRNOGS a Lotus collective", "category": "logo", "preview": "/projects_new/1x/Artboard 3.png", "description": "Série plakátů vytvořená pro BRNOGS a kolektiv Lotus. Vizuální styl pracuje s typografií ve velkých měřítkách, kontrastem forem a rytmem textu jako grafického prvku. Cílem bylo vytvořit sadu materiálů, které jsou odvážné, výrazné a zároveň funkční – připravené pro použití ve veřejném prostoru.", "images": ["/projects_new/1x/Artboard 3.png"]},
  {"title": "Plakáty pro eventy BRNOGS", "category": "ui/ux", "preview": "/projects_new/1x/Artboard 4.png", "description": "Série plakátů vytvořená pro eventy BRNOGS – nezávislé platformy propojující klubovou hudbu, komunitní energii a vizuální kulturu. Vizuální řešení pracuje s extrémní typografií, abstrahovanou mřížkou a rytmizovaným textem jako hlavním motivem. Každý plakát je navržen jako vizuální beat – rezonuje s hudebním programem a přitom drží jasnou identitu. Plakáty byly distribuovány jak online, tak fyzicky – často i jako součást urban kontextu, na sloupech nebo zdech města.", "images": ["/projects_new/1x/Artboard 4.png"]},
  {"title": "Typo vizuál pro festival ŠUŘKA a festival Encounter ", "category": "tisk", "preview": "/projects_new/1x/Artboard 5.png", "description": "Typografická práce pro festivalovou prezentaci – hlavním motivem je hra s prostorem pomocí textu. Používáme vrstvené texty a kontrastní velikosti písma, aby vznikl rytmus, který je vizuálně výrazný i ve větším formátu.", "images": ["/projects_new/1x/Artboard 5.png"]},
  {"title": "Plakát pro inscenaci Atlantis a event Tenacetum", "category": "web", "preview": "/projects_new/1x/Artboard 6.png", "description": "Dvojice plakátů vytvořená pro dvě rozdílná, ale vizuálně spřízněná kulturní díla: divadelní inscenaci Atlantis a hudební event Tenacetum. Atlantis pracuje s motivem ztracené civilizace — pomocí tekutých forem, rozpadlé typografie a iluzivního prostoru evokuje ponoření a mýtus. Výsledný vizuál osciluje mezi archeologií a futurismem. Tenacetum čerpá z organických struktur, vrstev a vizuálního chaosu, který reaguje na přírodní rytmy i klubové prostředí. Typografie zde funguje jako textura i signál. Oba plakáty propojuje práce s pohybem, vrstevnatostí a napětím mezi strukturou a intuicí.", "images": ["/projects_new/1x/Artboard 6.png"]},
  {"title": "Cover pro event tenacetuma pro kapelu meta and her noises", "category": "branding", "preview": "/projects_new/1x/Artboard 7.png", "description": "Návrh dvojice coverů, které spojuje intuitivní kompozice, rytmus a vrstvení obrazových prvků. Tenacetum je hudební event, jehož vizuál vychází z organických struktur, vizuálního šumu a postupně se skládajícího chaosu. Grafická textura vznikla vrstvením typografie, detailních výřezů a fragmentů inspirovaných přírodním řádem. Meta and Her Noises je kapela pohybující se na hranici elektroniky, tempa a zvukové koláže. Cover pro jejich release pracuje s digitálním kolapsem, šumem a přepětím – obraz evokuje jak analogový glitch, tak introspektivní ticho. Oba cover designy jsou založené na pohybu, napětí a pocitu proudící energie.", "images": ["/projects_new/1x/Artboard 7.png"]},
  {"title": "Covery pro meta and her noises", "category": "tisk", "preview": "/projects_new/1x/Artboard 8.png", "description": "Vizuální návrh obalu pro hudební projekt Meta and Her Noises. Design zkoumá vztah mezi digitálním kolapsem a emocionální introspekcí. Práce s texturou, šumem, glitch efektem a rozostřenou strukturou vytváří vizuální napětí, které odráží sonický charakter kapely – mezi ambientem, elektronikou a zvukovou dekonstrukcí. Cover funguje jako vizuální zvuková vlna – neklidná, fragmentovaná a zároveň soustředěná dovnitř.", "images": ["/projects_new/1x/Artboard 8.png"]},
  {"title": "Magazine fetish", "category": "web", "preview": "/projects_new/1x/Artboard 9.png", "description": "Fetish je magazínový experiment zkoumající posedlost, opakování a vizuální rituály. Vizuální jazyk je založený na vrstvení obrazů, agresivní typografii, fragmentaci a rytmickém opakování motivů. Každá stránka funguje jako izolovaný artefakt, ale v kontextu celku skládá narativ o estetické přepjatosti a tělesnosti médií. Projekt stojí na pomezí mezi grafickým designem a vizuálním výzkumem – fetiš jako forma i forma jako fetiš..", "images": ["/projects_new/1x/Artboard 9.png"]},
  {"title": "Logo pro meta and her noises", "category": "info", "preview": "/projects_new/1x/Artboard 10.png", "description": "Logo navržené pro hudební projekt Meta and Her Noises, který osciluje mezi abstraktním popem, noisovou estetikou a zvukovou koláží. Typografie byla rozkládána, dekonstruována a znovu skládána do znaku, který reflektuje charakter kapely – fragmentovaný, vrstvený, rytmický. Výsledný logotyp balancuje mezi čitelností a grafickou expresí. Je navržen tak, aby fungoval jak staticky, tak v pohybu – například ve vizuálech na sociálních sítích nebo jako motion intro.", "images": ["/projects_new/1x/Artboard 10.png"]},
  {"title": "Claim pro fetish magazine", "category": "tisk", "preview": "/projects_new/1x/Artboard 11.png", "description": "Logotyp navržený pro konceptuální publikaci Fetish Magazine, která tematizuje posedlost, repeticí a estetický tlak. Návrh se odchyluje od tradiční funkce loga – místo jasné identifikace slouží jako výrazová struktura. Písmena jsou rozvolněná, posunutá mimo osu a fragmentovaná do napětí mezi čitelností a autonomním obrazem. Logotyp se tak stává fetišem samotným – objektem, který poutá pozornost a nedává se okamžitě přečíst.", "images": ["/projects_new/1x/Artboard 11.png"]}
]

export default function Portfolio() {
  const [selected, setSelected] = useState(null)

  return (
    <div className="p-6 max-w-6xl mx-auto">
      <h2 className="text-xl font-bold mb-4">Portfolio</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
        {projects.map((p, idx) => (
          <div key={idx} className="group relative border rounded overflow-hidden hover:shadow-lg transition cursor-pointer"
               onClick={() => setSelected(p)}>
            <img src={p.preview} alt={p.title} className="w-full h-56 object-cover group-hover:scale-105 transition duration-300" />
            <div className="absolute bottom-0 left-0 right-0 bg-white bg-opacity-90 p-2 text-sm font-semibold text-black">
              {p.title} <span className="text-xs text-gray-500 ml-2">({p.category})</span>
            </div>
          </div>
        ))}
      </div>
      <ProjectModal project={selected} onClose={() => setSelected(null)} />
    </div>
  )
}